### ISSUE TITLE
Map HOME button on the Kinova joystick to the VIVE controller

### ISSUE THREAD

**Issue by SpaceVR-O1** [SpaceVR-O1/Human#5] opened 2017-07-14 04:46 UTC

**Comment by aornelas** [comment] 2017-07-14 04:58
The workaround is to have the Kinova joystick nearby and press the HOME button there; definitely not ideal, but works while this is done.

**Comment by aornelas** [comment] 2017-07-14 07:12
Duplicate of #3

**Closed as completed by aornelas** 2017-07-14 07:12 UTC
Labels: enhancement
